version: 2

build:
  os: ubuntu-22.04
  tools:
    python: mambaforge-latest
  commands:
    - micromamba install -c conda-forge -c nodefaults --yes --file docs/environment.yml
    - python -m pip install .
    - jupyter lite build
    - rm -rf $READTHEDOCS_OUTPUT/html && cp -r dist $READTHEDOCS_OUTPUT/html
